apiVersion: apps/v1
kind: Deployment
metadata:
  name: ResidentQnA
  labels:
    app: ResidentQnA
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ResidentQnA
  template:
    metadata:
      labels:
        app: ResidentQnA
    spec:
      containers:
        - name: ResidentQnA
          image: "username/ResidentQnA:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
