apiVersion: apps/v1
kind: Deployment
metadata:
  name: AuditLog
  labels:
    app: AuditLog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: AuditLog
  template:
    metadata:
      labels:
        app: AuditLog
    spec:
      containers:
        - name: AuditLog
          image: "username/AuditLog:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
