apiVersion: apps/v1
kind: Deployment
metadata:
  name: QnAEngine
  labels:
    app: QnAEngine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: QnAEngine
  template:
    metadata:
      labels:
        app: QnAEngine
    spec:
      containers:
        - name: QnAEngine
          image: "username/QnAEngine:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
